// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:theway_mobile/features/books/data/models/saved_book_model.dart';
import 'package:theway_mobile/features/cbt/data/models/delta_checkpoint_model.dart';
import 'package:theway_mobile/features/cbt/data/models/exam_type_model.dart';
import 'package:theway_mobile/features/cbt/data/models/offline_session_model.dart';
import 'package:theway_mobile/features/cbt/data/models/pending_operation_model.dart';
import 'package:theway_mobile/features/cbt/data/models/question_model.dart';
import 'package:theway_mobile/features/cbt/data/models/question_passage_group_model.dart';
import 'package:theway_mobile/features/cbt/data/models/subject_model.dart';
import 'package:theway_mobile/features/cbt/data/models/topic_model.dart';
import 'package:theway_mobile/features/video/data/models/downloaded_video_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DeltaCheckpointModelAdapter());
    registerAdapter(DownloadedVideoModelAdapter());
    registerAdapter(ExamTypeModelAdapter());
    registerAdapter(ExamTypeSubjectRefAdapter());
    registerAdapter(OfflineSessionModelAdapter());
    registerAdapter(PendingOperationAdapter());
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionPassageGroupModelAdapter());
    registerAdapter(SavedBookModelAdapter());
    registerAdapter(SubjectModelAdapter());
    registerAdapter(TopicModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DeltaCheckpointModelAdapter());
    registerAdapter(DownloadedVideoModelAdapter());
    registerAdapter(ExamTypeModelAdapter());
    registerAdapter(ExamTypeSubjectRefAdapter());
    registerAdapter(OfflineSessionModelAdapter());
    registerAdapter(PendingOperationAdapter());
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionPassageGroupModelAdapter());
    registerAdapter(SavedBookModelAdapter());
    registerAdapter(SubjectModelAdapter());
    registerAdapter(TopicModelAdapter());
  }
}
